export const ADD_BOARD = 'ADD_BOARD';
export const EDIT_BOARD_TITLE = 'EDIT_BOARD_TITLE';
export const EDIT_BOARD_COLOR = 'EDIT_BOARD_COLOR';
export const MOVE_LIST = 'MOVE_LIST';
export const MOVE_LIST_TO_ANOTHER_BOARD = 'MOVE_LIST_TO_ANOTHER_BOARD';
export const DELETE_BOARD = 'DELETE_BOARD';

