export const REQUEST_BOARDS = 'REQUEST_BOARDS';
export const RESPONSE_BOARDS_SUCCESS = 'RESPONSE_BOARDS_SUCCESS';
export const SET_CURRENT_BOARD_ID = 'SET_CURRENT_BOARD_ID';
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

