export const ADD_CARD = 'ADD_CARD';
export const ADD_LABEL_TO_CARD = 'ADD_LABEL_TO_CARD';
export const EDIT_CARD_TITLE = 'EDIT_CARD_TITLE';
export const EDIT_CARD_DESCRIPTION = 'EDIT_CARD_DESCRIPTION';
export const DELETE_CARD = 'DELETE_CARD';
